version: 3
tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist/

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  build:
    desc: Build application
    cmds:
      - task: clean
      - go build -o ./dist/ ./cmd/rmqbe

  # builds a fully static Linux binary of Go application
  # - CGO_ENABLED=0 disables CGO for full static linking
  # - GOOS=linux targets Linux (cross-compilation if needed)
  # - -a rebuilds all packages
  # - -installsuffix cgo separates CGO-disabled build artifacts from any CGO-enabled ones
  # - -ldflags '-extldflags "-static"' ensures the binary is statically linked (no libc dependency)
  # - -o rmqbe sets the output binary name
  build-prod:
    desc: Build application for production
    cmds:
      - task: clean
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o ./dist/ ./cmd/rmqbe
